name: Ping

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  ping:
    name: Ping unupdated WIP entry
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go mod download

      - name: Ping
        run: go run main.go
        env:
          # admin@camph.net で発行したPersonal access token
          ESA_API_TOKEN: ${{ secrets.ESA_API_TOKEN }}
